services:
  - type: web
    name: paradigm-pricing
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_CREDENTIALS_FILE
        value: credentials.json
      - key: GOOGLE_SHEET_NAME
        value: pricing-investment-fund
      - key: GOOGLE_SHEET_URL
        sync: false  # À configurer manuellement dans Render
